from inspect import Signature
from typing import Callable

def num_required_args(func: Callable[..., object], sigspec: Signature | None = ...) -> int | None: ...
def has_varargs(func: Callable[..., object], sigspec: Signature | None = ...) -> bool | None: ...
def has_keywords(func: Callable[..., object], sigspec: Signature | None = ...) -> bool | None: ...
def is_valid_args(func: Callable[..., object], args: tuple[object, ...], kwargs: dict[str, object], sigspec: Signature | None = ...) -> bool | None: ...
def is_partial_args(func: Callable[..., object], args: tuple[object, ...], kwargs: dict[str, object], sigspec: Signature | None = ...) -> bool | None: ...
def is_arity(n: int, func: Callable[..., object], sigspec: Signature | None = ...) -> bool | None: ...
