from collections.abc import Callable, Iterable, Iterator
from typing import TypeVar, overload

T = TypeVar('T')
A = TypeVar('A')
R = TypeVar('R')

def remove(predicate: Callable[[T], object], seq: Iterable[T]) -> Iterator[T]: ...

@overload
def accumulate(binop: Callable[[T, T], T], seq: Iterable[T]) -> Iterator[T]: ...
@overload
def accumulate(binop: Callable[[A, T], A], seq: Iterable[T], initial: A) -> Iterator[A]: ...

def cons(el: T, seq: Iterable[T]) -> Iterator[T]: ...
def interpose(el: T, seq: Iterable[T]) -> Iterator[T]: ...
def interleave(seqs: Iterable[Iterable[T]]) -> Iterable[T]: ...
def iterate(func: Callable[[T], T], x: T) -> Iterator[T]: ...
def concat(seqs: Iterable[Iterable[T]]) -> Iterator[T]: ...
def concatv(*seqs: Iterable[T]) -> Iterator[T]: ...
def mapcat(func: Callable[[T], Iterable[R]], seqs: Iterable[T]) -> Iterator[R]: ...
