from collections.abc import Iterable, Iterator
from typing import Literal, TypeVar, TypeVarTuple, overload

T = TypeVar('T')
A1 = TypeVar('A1')
A2 = TypeVar('A2')
A3 = TypeVar('A3')
A4 = TypeVar('A4')
A5 = TypeVar('A5')
A6 = TypeVar('A6')
A7 = TypeVar('A7')
A8 = TypeVar('A8')
A9 = TypeVar('A9')
A10 = TypeVar('A10')
A11 = TypeVar('A11')
Ts = TypeVarTuple('Ts')

@overload
def nth(n: Literal[0], seq: tuple[A1, *Ts]) -> A1: ...
@overload
def nth(n: Literal[1], seq: tuple[A1, A2, *Ts]) -> A2: ...
@overload
def nth(n: Literal[2], seq: tuple[A1, A2, A3, *Ts]) -> A3: ...
@overload
def nth(n: Literal[3], seq: tuple[A1, A2, A3, A4, *Ts]) -> A4: ...
@overload
def nth(n: Literal[4], seq: tuple[A1, A2, A3, A4, A5, *Ts]) -> A5: ...
@overload
def nth(n: Literal[5], seq: tuple[A1, A2, A3, A4, A5, A6, *Ts]) -> A6: ...
@overload
def nth(n: Literal[6], seq: tuple[A1, A2, A3, A4, A5, A6, A7, *Ts]) -> A7: ...
@overload
def nth(n: Literal[7], seq: tuple[A1, A2, A3, A4, A5, A6, A7, A8, *Ts]) -> A8: ...
@overload
def nth(n: Literal[8], seq: tuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, *Ts]) -> A9: ...
@overload
def nth(n: Literal[9], seq: tuple[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, *Ts]) -> A10: ...
@overload
def nth(n: int, seq: Iterable[T]) -> T: ...

@overload
def first(seq: tuple[T, *Ts]) -> T: ...
@overload
def first(seq: Iterable[T]) -> T: ...

@overload
def second(seq: tuple[A1, T, *Ts]) -> T: ...
@overload
def second(seq: Iterable[T]) -> T: ...

@overload
def last(seq: tuple[*Ts, T]) -> T: ...
@overload
def last(seq: Iterable[T]) -> T: ...

def rest(seq: Iterable[T]) -> Iterator[T]: ...

def peek(seq: Iterable[T]) -> tuple[T, Iterator[T]]: ...

def peekn(n: int, seq: Iterable[T]) -> tuple[list[T], Iterator[T]]: ...
