from collections.abc import Iterable, Iterator
from typing import TypeVar

T = TypeVar('T')

def take(n: int, seq: Iterable[T]) -> list[T]: ...
def tail(n: int, seq: Iterable[T]) -> list[T]: ...
def drop(n: int, seq: Iterable[T]) -> Iterator[T]: ...
def take_nth(n: int, seq: Iterable[T]) -> Iterator[T]: ...
