from collections.abc import Iterable
from typing import TypeIs

def isiterable(x: object) -> TypeIs[Iterable[object]]: ...
def isdistinct(seq: Iterable[object]) -> bool: ...
def count(seq: Iterable[object]) -> int: ...
